[project]
name = "multi-reader"
version = "0.1.0"
description = "An app for expanding vulacublary"
readme = "README.md"
authors = [
    { name = "KoskeK", email = "koskekanasugi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "deep-translator>=1.11.4",
    "pymupdf>=1.28.2",
    "pyside6>=6.11.1",
]
license = "MIT"

[project.scripts]
multi-reader = "multi_reader:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
